// dummy
// id,
// name,
// price,
// images,
// city,
// country,
export const KOST_ROOM = [
  {
    id: 1,
    name: "Mawar Kost",
    price: 200000,
    images: [
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102646/cld-sample-4.jpg",
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102645/cld-sample-2.jpg",
    ],
    city: "Jakarta",
    country: "Indonesia",
    address: "Jl Panglima Polim",
    facilities: ["wifi", "netflix", "kamar mandi dalam"],
    availability: true,
  },
  {
    id: 2,
    name: "Melati Kost",
    price: 300000,
    images: [
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102647/cld-sample-5.jpg",
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102646/cld-sample-3.jpg",
    ],
    city: "Depok",
    country: "Indonesia",
    address: "Jl Panglima Polim",
    facilities: ["wifi", "netflix", "kamar mandi dalam"],
    availability: true,
  },
  {
    id: 3,
    name: "Tulip Homestay",
    price: 500000,
    images: [
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102644/cld-sample.jpg",
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102618/sample.jpg",
    ],
    city: "Padang",
    country: "Indonesia",
    address: "Jl Panglima Polim",
    facilities: ["wifi", "netflix", "kamar mandi dalam"],
    availability: true,
  },
  {
    id: 4,
    name: "Honu lulu",
    price: 580000,
    images: [
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102618/sample.jpg",
      "https://res.cloudinary.com/dkg0oswii/image/upload/v1669102644/cld-sample.jpg",
    ],
    city: "Padang",
    country: "Indonesia",
    address: "Jl Panglima Polim",
    facilities: ["wifi", "netflix", "kamar mandi dalam"],
    availability: true,
  },
];
